export const FETCH_ADMIN_START = "FETCH_ADMIN_START";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILURE = "FETCH_ADMIN_FAILURE";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";